services:
  api-gateway:
    image: ${DOCKERHUB_USERNAME}/cafe-api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - payment-service
      - order-service
      - menu-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  payment-service:
    image: ${DOCKERHUB_USERNAME}/cafe-payment-service:latest
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  order-service:
    image: ${DOCKERHUB_USERNAME}/cafe-order-service:latest
    ports:
      - "3002:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order-db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - cafe-network

  menu-service:
    image: ${DOCKERHUB_USERNAME}/cafe-menu-service:latest
    ports:
      - "3003:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/menu-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  inventory-service:
    image: ${DOCKERHUB_USERNAME}/cafe-inventory-service:latest
    ports:
      - "3004:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/inventory-db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - cafe-network

  customer-service:
    image: ${DOCKERHUB_USERNAME}/cafe-customer-service:latest
    ports:
      - "3005:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/customer-db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - cafe-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cafe-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - cafe-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge

volumes:
  mongodb_data: 