
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - payment-service
      - order-service
      - menu-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  payment-service:
    build: ./payment-services
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  order-service:
    build: ./order-services
    ports:
      - "3002:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  menu-service:
    build: ./menu-services
    ports:
      - "3003:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/menu-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  inventory-service:
    build: ./inventory-services
    ports:
      - "3004:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/inventory-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  customer-service:
    build: ./customer-services
    ports:
      - "3005:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/customer-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cafe-network

  

networks:
  cafe-network:
    driver: bridge

volumes:
  mongodb_data: 