name: All Services CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/all-services.yml'

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:buildcache,mode=max

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./payment-services
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-payment-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-payment-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-payment-service:buildcache,mode=max

      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order-services
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-order-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-order-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-order-service:buildcache,mode=max

      - name: Build and push Menu Service
        uses: docker/build-push-action@v4
        with:
          context: ./menu-services
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-menu-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-menu-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-menu-service:buildcache,mode=max

      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-services
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-inventory-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-inventory-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-inventory-service:buildcache,mode=max

      - name: Build and push Customer Service
        uses: docker/build-push-action@v4
        with:
          context: ./customer-services
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-customer-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-customer-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-customer-service:buildcache,mode=max 