name: API Gateway CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cafe-api-gateway:buildcache,mode=max 